### ISSUE TITLE
Support nested methods

### ISSUE THREAD

**Issue by basco-johnkevin** [angular-pouchdb/angular-pouchdb#13]
I'm trying to use this plugin https://github.com/nolanlawson/relational-pouch while using angular-pouchdb but I can't make it work.

I'm getting this error `TypeError: undefined is not a function` using this code:

```
db.setSchema([
  {
    singular: 'expense',
    plural: 'expenses',
  }
]);
```

To fix it I added:
```
pouchDBProvider.methods = POUCHDB_DEFAULT_METHODS.concat([
  'setSchema',
]);
```

Now the error is gone, but I'm not able to call the methods that should be added by relational pouch
```
db.rel.save('expense', {
  title: 'Rails is Omakase',
  text: 'There are a lot of a-la-carte software...'
});
```
 TypeError: Cannot read property 'save' of undefined

I tried adding rel:
```
    pouchDBProvider.methods = POUCHDB_DEFAULT_METHODS.concat([
      'setSchema',
      'rel',
    ]);
```
But I'm getting this error: TypeError: Cannot read property 'bind' of undefined at http://localhost:8100/lib/angular-pouchdb/dist/angular-pouchdb.js:53:40

**Comment by tlvince** [comment]
Ah, relational-pouch uses nested methods, whereas angular-pouchdb assumes a flat level list. Since I've already hardcoded [db.replicate.*](https://github.com/angular-pouchdb/angular-pouchdb/blob/ec2a370071cb195e05e5c30585849c45bb968f58/angular-pouchdb.js#L65) in, we should add support for this.

In the meantime, you're probably best off using relational-pouch directly (and wrapping its methods accordingly).

**Comment by basco-johnkevin** [comment]
@tlvince Thanks for the response. Will be using it directly in the meantime. Happy new year! :)
