### ISSUE TITLE
Copy adapter object from PouchDB instance

### ISSUE THREAD

**Issue by PabloDeGrote** [angular-pouchdb/angular-pouchdb#32]
Hi there, (great to see a new repo!)

I want to know what kind of adapter the clientside is using (i.e. 'idb' or 'websql') but angular-pouchdb will not copy this value over.

Simple fix would be to add ``api.adapter = db.adapter;`` after looping through the methods.

**Comment by tlvince** [comment]
Hi @PabloDeGrote, this is fixed in [develop](https://github.com/angular-pouchdb/angular-pouchdb/blob/develop/angular-pouchdb.js) (where the PouchDB object is passed through intact).

You may give that a try for now, or wait for the next release (though I've got [quite a few issues](https://github.com/angular-pouchdb/angular-pouchdb/milestones/v1.1.0)) to get through).

**Comment by PabloDeGrote** [comment]
Sweet that works and is a great solution. I really like the short codes.

Good luck on the 1.1.0 release!

**Comment by tlvince** [comment]
Closed by 1c600e956ce0464306ea594ccac3fc176682cde7.
