### ISSUE TITLE
$scope isn't updated sometimes

### ISSUE THREAD

**Issue by Dazzel** [angular-pouchdb/angular-pouchdb#47]
Plugins I'am using:
[pouchdb-find](https://github.com/nolanlawson/pouchdb-find) 
[ui-router](https://github.com/angular-ui/ui-router)

My ui-router states are roughly like this:

```
.state('state1', {
      url: "/",
      abstract: true,
      templateUrl: "partials/state1.html"
    })
    .state('state1.list', {
      url: "/list",
      templateUrl: "partials/state1.list.html",
      controller: "State1ListCtrl"
    })
    .state('state1.view', {
      url: "/view/:id",
      templateUrl: "partials/state1.view.html",
      controller: "State1ListCtrl"
    })
```

The `State1ListCtrl` loads some docs into $scope and they are displayed on the initial load. Now changeing to one specific doc and moving to `/view/:id` only this view is displayed. So far, so good.
But now if we move back to `/list` nothing is displayed. This issue only occures sometimes. Only the scoped is not updated.

Printing the result from `db.find({...})` to the console works as espected: On every page change the resultes are fetched from pouchdb.

An workaround was, to encapsulate `db.find({...})` into `$timeout` with an delay of 10ms. Then the scope is updated every time.

Using version 2.0.1

**Comment by tlvince** [comment]
Would you be able to provide a reduced test case (plunkr or the like)?

**Comment by Dazzel** [comment]
Here you go: http://embed.plnkr.co/QkIxrozRMv1tAcVGYNiS/preview

Strange thing is, that the $timeout workaround does not work on plunkr. Might be a version conflict. Using the .js from your dist folder.

**Comment by tlvince** [comment]
Thanks for that!

There's two things at play here.

Firstly, since angular-pouchdb only wraps PouchDB's [core API](https://github.com/angular-pouchdb/angular-pouchdb/blob/0de5f857e719fba0021d51f45573afce4e4e5344/angular-pouchdb.js#L4-L25) by default, you have to add methods defined by plugins [manually](https://github.com/angular-pouchdb/angular-pouchdb/tree/0de5f857e719fba0021d51f45573afce4e4e5344#options).

However, as it seems that `db.find` is added *after* instantiation (perhaps [via a promise](https://github.com/angular-pouchdb/angular-pouchdb/issues/43#issuecomment-90612495)), "qify" does not get applied, hence why your scope doesn't automatically update.

As a workaround, we can manually apply qify after instantiation to get the desired effect, e.g.:

```js
angular.controller('myCtrl', function(pouchDB, pouchDecorators) {
  var db = pouchDB('db');
  db.find = pouchDecorators.qify(db.find);
});
```

See it working in a [fork of your plunkr](http://plnkr.co/edit/qlnR7MZB1194lMsxMoYN?p=preview), with annotations.

I've yet to find a better solution (see #37 for a similar issue), but will add a note to the readme with this workaround.

**Comment by Dazzel** [comment]
Great! Thanks for the fast reply :)
