### ISSUE TITLE
Compatibility with Angular 2?

### ISSUE THREAD

**Issue by PaulCapestany** [angular-pouchdb/angular-pouchdb#94]
I've been using other JS frameworks till now, however Angular 2 recently caught my interest. Before diving too deep into the weeds though, I was wondering if this plugin is compatible with Angular2?

**Comment by tlvince** [comment]
It targets Angular 1.x and I've yet to experiment with Angular 2.x, so I'm not sure. Would be good if someone could confirm this.

**Comment by gustavohenke** [comment]
How curious, I have just started trying out Angular 2 today :)
From what it seems, no, by default angular-pouchdb is not compatible with it.

- Angular 2 is built around ES6 classes, so some work would be needed to migrate the current provider.
- Another point is that [there isn't something like `$scope.$apply()` anymore](http://stackoverflow.com/a/33175487/2083599), because it is not needed

So, as someone who's been studying Angular 2 for a few hours... angular-pouchdb seems to have been outdated.

**Comment by nolanlawson** [comment]
Is there any reason you couldn't use PouchDB directly with Angular 2? My understanding is that Angular 2 embraces the wider JS conventions more than Angular 1 (e.g. ES modules instead of Angular's module system). Throw in DefinitelyType's TypeScript definitions for PouchDB, and it should be just a `npm install pouchdb` away, right?

**Comment by chrismclarke** [comment]
There's a good example using pouchdb with ionic (built on angular 2) here:
http://www.joshmorony.com/syncing-data-with-pouchdb-and-cloudant-in-ionic-2/

Ionic uses browserfy to pull in modules and build. Alternatively you could try with webpack or as suggested just linking script tags. A few discussions around these are here:
https://webcake.co/add-pouchdb-to-an-ionic-2-app-via-webpack/

**Comment by tigerxy** [comment]
If you use **angular-cli** you can simply install it with `npm install pouchdb --save`. Then you have to register it in `angular-cli-build.js` [Guide](/angular/angular-cli/wiki/3rd-party-libs)
```
vendorNpmFiles: [
      'pouchdb/dist/pouchdb.js'
    ]
```
 and `src/system-config.ts`
```
const map: any = {
  'PouchDB': 'vendor/pouchdb/dist/pouchdb.js'
};
```
At least you must set a reference to the `pouch.d.ts`. You can download my newer version here: [Typescript Definition](/DefinitelyTyped/DefinitelyTyped/pull/6365) (you need also levelup.d.ts)
```
/// <reference path="pouchDB/pouch.d.ts" />
```
In your controller or service you can import and use it with
```
import { PouchDB } from 'PouchDB';
this.db = new PouchDB('my-db');
```

**Comment by warria1** [comment]
Hi,

Can you please tell me how I can configure PouchDB, if I am using SystemJS. This is how my systemjs.config.js looks like now:

```
/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function(global) {
  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  };
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages
  }
  System.config(config);
})(this);

```

**Comment by narottamgoyal** [comment]
Hello tigerxy, I tried what ever you explained and its not working for me, Could you please help here...

https://github.com/narottamgoyal/ElectronWithPouchDb.git


Thank you!
narottam.in@gmail.com

**Comment by NNemec** [comment]
I'm using PouchDB with Angular2 - it works fine except that change events do not run inside the NgZone, so that the UI is not automatically updated when database changes occur. I can work around this by wrapping the individual event handlers in NgZone.run(), but that is increasingly annoying and error prone.

Has anyone else experienced this? Is there any way to generally move the change events into the NgZone?

**Comment by hboylan** [comment]
This was marked as resolved, but I still don't see an official solution. Are there any plans to add Typescript support for Angular 2?

**Comment by tlvince** [comment]
There are no plans. I [recommend](https://github.com/angular-pouchdb/angular-pouchdb#does-this-work-with-angular-v2) you use PouchDB directly.

**Comment by hboylan** [comment]
Fair enough, thanks.
Would be nice to use Typescript's autocomplete feature, but will take what I can get. 😄

**Comment by lakinmohapatra** [comment]
Use this typings  - npm install --save @types/pouchdb
https://www.npmjs.com/package/@types/pouchdb

And then use
 import PouchDB from 'pouchdb'; in any typescript file and you will be able to access db.
